#!/usr/bin/env python3
"""Compose self-contained reading skills from shared authoring sources."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "skill-src"
TARGETS = {
    "quick": ROOT / "skills" / "clear-eyed-reading",
    "deep": ROOT / "skills" / "clear-eyed-deep-reading",
}
METADATA_KEYS = {
    "name",
    "description",
    "display_name",
    "short_description",
    "default_prompt",
}


def parse_profile(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter")
    frontmatter, separator, body = text[4:].partition("\n---\n")
    if not separator:
        raise ValueError(f"{path}: unterminated frontmatter")

    metadata: dict[str, str] = {}
    for line in frontmatter.splitlines():
        key, separator, value = line.partition(":")
        if not separator or key not in METADATA_KEYS:
            raise ValueError(f"{path}: unsupported metadata line: {line}")
        metadata[key] = json.loads(value.strip())

    missing = METADATA_KEYS - metadata.keys()
    if missing:
        raise ValueError(f"{path}: missing metadata: {', '.join(sorted(missing))}")
    return metadata, body.strip()


def quote_yaml(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_skill(metadata: dict[str, str], profile: str) -> str:
    core = (SOURCE_ROOT / "core.md").read_text(encoding="utf-8").strip()
    output = (SOURCE_ROOT / "output" / "chat.md").read_text(encoding="utf-8").strip()
    return (
        "---\n"
        f"name: {metadata['name']}\n"
        f"description: {metadata['description']}\n"
        "---\n\n"
        "<!-- Generated by scripts/sync_skills.py; edit skill-src instead. -->\n\n"
        f"{core}\n\n{profile}\n\n{output}\n"
    )


def render_openai_yaml(metadata: dict[str, str]) -> str:
    return (
        "interface:\n"
        f"  display_name: {quote_yaml(metadata['display_name'])}\n"
        f"  short_description: {quote_yaml(metadata['short_description'])}\n"
        f"  default_prompt: {quote_yaml(metadata['default_prompt'])}\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n"
    )


def expected_files() -> dict[Path, str]:
    files: dict[Path, str] = {}
    for profile_name, target in TARGETS.items():
        metadata, body = parse_profile(SOURCE_ROOT / "depth" / f"{profile_name}.md")
        files[target / "SKILL.md"] = render_skill(metadata, body)
        files[target / "agents" / "openai.yaml"] = render_openai_yaml(metadata)
    return files


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="report generated files that differ without writing them",
    )
    args = parser.parse_args()

    stale: list[Path] = []
    for path, expected in expected_files().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")

    if args.check and stale:
        for path in stale:
            print(path.relative_to(ROOT))
        return 1
    if not args.check:
        for path in stale:
            print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
